version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./media:/app/media  # Ensure media files persist
      - ./static:/app/static # Ensure static files persist

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./start-nginx.sh:/start-nginx.sh
      - ./media:/media  # Serve media files via Nginx
      - ./static:/static
    entrypoint: [ "/bin/bash", "/start-nginx.sh" ]
    depends_on:
      - web

volumes:
  postgres-db:
  web:
  nginx:
